package com.safeqr.scanner.utils

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.widget.Toast
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfExportUtils {

    suspend fun exportQrAsPdf(context: Context, qrBitmap: Bitmap, title: String, description: String = "") {
        withContext(Dispatchers.IO) {
            try {
                val pdfDocument = PdfDocument()
                // A4 page size in points (1/72 inch). 595 x 842 points
                val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
                val page = pdfDocument.startPage(pageInfo)
                val canvas = page.canvas
                val paint = Paint()

                // Draw background
                paint.color = Color.WHITE
                canvas.drawRect(0f, 0f, 595f, 842f, paint)

                // Draw Header text (Branding)
                paint.color = Color.parseColor("#0A84FF") // NeonCyan approximate
                paint.textSize = 28f
                paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                paint.textAlign = Paint.Align.CENTER
                canvas.drawText("ThreatLens Safe QR", 595f / 2, 80f, paint)

                // Draw Title
                paint.color = Color.BLACK
                paint.textSize = 24f
                paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                canvas.drawText(title, 595f / 2, 140f, paint)

                // Draw Description
                if (description.isNotEmpty()) {
                    paint.textSize = 16f
                    paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                    paint.color = Color.DKGRAY
                    canvas.drawText(description, 595f / 2, 170f, paint)
                }

                // Draw QR Code
                // Target QR size: 300x300 points
                val qrSize = 300f
                val left = (595f - qrSize) / 2
                val top = 220f
                val scaledQr = Bitmap.createScaledBitmap(qrBitmap, qrSize.toInt(), qrSize.toInt(), true)
                canvas.drawBitmap(scaledQr, left, top, null)

                // Draw Footer
                paint.textSize = 12f
                paint.color = Color.GRAY
                paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
                canvas.drawText("Generated by ThreatLens QR Studio", 595f / 2, 800f, paint)

                pdfDocument.finishPage(page)

                // Save to Downloads directory
                val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
                val fileName = "ThreatLens_QR_$timestamp.pdf"
                val file = File(downloadsDir, fileName)

                pdfDocument.writeTo(FileOutputStream(file))
                pdfDocument.close()

                withContext(Dispatchers.Main) {
                    Toast.makeText(context, "Saved PDF to Downloads", Toast.LENGTH_LONG).show()
                }

            } catch (e: Exception) {
                e.printStackTrace()
                withContext(Dispatchers.Main) {
                    Toast.makeText(context, "Failed to export PDF: ${e.message}", Toast.LENGTH_LONG).show()
                }
            }
        }
    }
}
